spring:
    application:
        name: BankManagementService
    datasource:
        url: ${DB_URI}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driverClassName: org.h2.Driver
  
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    h2:
#        console:
#            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
            format-sql: true
    mail:
        host: smtp.gmail.com
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp: 
                    auth: true
                    starttls:
                        enable: true
# logging:
#     level:
#         root: debug

jwt:
    secret: ${JWT_SECRET}





