spring:
    application:
        name: BankManagementService
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASWWORD}
        driverClassName: org.h2.Driver
  
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    h2:
#        console:
#            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        # show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_SERVER_USERNAME}
        password: ${EMAIL_SERVER_PASSWORD}
        properties:
            mail:
                smtp: 
                    auth: true
                    starttls:
                        enable: true
# logging:
#     level:
#         root: debug






