spring:
    application:
        name: BankManagementService
    mail:
        host: smtp.gmail.com
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    datasource:
        url: ${DB_URI}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driverClassName: org.h2.Driver

jwt:
    secret: ${JWT_SECRET}

liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"


