spring:
    application:
        name: prestaSavings
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: <****>
        url: jdbc:mysql://localhost:3306/savings
        username: <****>
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true




