spring:
    application:
        name: BankManagementService
    datasource:
        url: jdbc:h2:./data/presta
        username: sa
        password: password
        driverClassName: org.h2.Driver
  
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    h2:
#        console:
#            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
# logging:
#     level:
#         root: debug



